### ISSUE TITLE
Ch5 Coin Sprite

### ISSUE THREAD

**Issue by houthkenny** [Apress/Devel-2D-Games-Unity#22]
Hi, I'm having trouble getting the coin sprite to be visible in the scene view. I've put the sorting layer to objects just like the book instructed, but for some reason the sprite still won't render, any help/ideas?

**Comment by houthkenny** [comment]
nvm I figured it out, After changing the camera view from 2d to 3d It showed the coin sprite wasn't in viewing parameters for the camera, playing around with positions on the coin object help fixed the issue.

**Comment by JaredHalpern** [comment]
Thanks for updating and closing the ticket @houthkenny

**Comment by scouttyg** [comment]
Note: I ran into the same problem here, and like @houthkenny mentioned, it was due to the `CoinObject` being set in a negative Z direction, which seems to have happened just by dragging the `CoinObject` into the Scene.

To fix this, in the **_Inspector_** for the `CoinObject`, look under the **_Transform_** section, in the **_Position_** attribute area. There should be coordinates for **_X_**, **_Y_**, and **_Z_**, which correspond to where the coin was placed within the Scene. Make sure that the **_Z_** attribute is not set to a negative value, as this will have it appear "below" the world. Setting this value to `0` should make it show up correctly.

**Comment by JaredHalpern** [comment]
Thanks so much for the feedback @scouttyg. I've noticed that Unity sometimes does this as well. Not sure why, and it's not consistent behavior. I might file a bug report with them.
